apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: petclinic
type: Opaque
data:
  POSTGRES_USER: cGV0Y2xpbmlj     # petclinic
  POSTGRES_PASSWORD: cGV0Y2xpbmljMTIz # petclinic123
  POSTGRES_DB: cGV0Y2xpbmlj      # petclinic