apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: local/nextjs:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: BASE_PATH
          value: "/nextjs"  # Set the base path dynamically