apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-config
  namespace: petclinic
data:
  SPRING_PROFILES_ACTIVE: postgres
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petclinic
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
  SERVER_SERVLET_CONTEXT_PATH: "/petclinic"