apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: docker.io/jayasb/petclinic:49941078b3f01ab2a396eb625f6f52ec298d79a9
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: petclinic-config
                key: SPRING_PROFILES_ACTIVE
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: petclinic-config
                key: SPRING_DATASOURCE_URL
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            valueFrom:
              configMapKeyRef:
                name: petclinic-config
                key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          - name: SERVER_SERVLET_CONTEXT_PATH
            valueFrom:
              configMapKeyRef:
                name: petclinic-config
                key: SERVER_SERVLET_CONTEXT_PATH
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"