name: PetClinic CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/petclinic/**'
      - '.github/workflows/petclinic.yml'

permissions:
  contents: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository_owner }}/petclinic
  K8S_MANIFEST_FILE: apps/petclinic/deployment.yaml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./apps/petclinic
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Update Kubernetes manifest
      run: |
        sed -i "s|image: .*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}|" ${{ env.K8S_MANIFEST_FILE }}

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add ${{ env.K8S_MANIFEST_FILE }}
        git commit -m "Update image tag to ${{ github.sha }}"
        git push
